# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.hostname="docker00"
  config.vm.box = "centos7"
  config.vm.network "private_network", ip: "192.168.33.20"
#  config.vbguest.auto_update=false
end
